"""empty message

Revision ID: 6c79706fe2ac
Revises: 
Create Date: 2025-08-09 12:36:32.068118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c79706fe2ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_adi', sa.String(), nullable=False),
    sa.Column('sifre_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kullanici_adi')
    )
    op.create_table('kitaplar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isim', sa.String(length=100), nullable=False),
    sa.Column('yazar', sa.String(length=100), nullable=False),
    sa.Column('yayin_yili', sa.Integer(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitaplar')
    op.drop_table('kullanicilar')
    # ### end Alembic commands ###
