"""Initial migration

Revision ID: c95c0b46e483
Revises: 
Create Date: 2025-12-19 15:01:58.678398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95c0b46e483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_adi', sa.String(length=100), nullable=False),
    sa.Column('sifre_hash', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kullanici_adi')
    )
    op.create_table('kitaplar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isim', sa.String(length=100), nullable=False),
    sa.Column('yazar', sa.String(length=100), nullable=False),
    sa.Column('sayfa_sayisi', sa.Integer(), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=False),
    sa.Column('yayin_yili', sa.Integer(), nullable=False),
    sa.Column('yayinevi', sa.String(length=100), nullable=False),
    sa.Column('okundu_mu', sa.Boolean(), nullable=False),
    sa.Column('kullanici_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitaplar')
    op.drop_table('kullanicilar')
    # ### end Alembic commands ###
